name: Build and Deploy
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Check Branch
    runs-on: bash
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Get Branch 
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          
      - name: Match Branch
        run: exit 1
          
          
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Checkout ..... Done
        
      - name: Install Dependencies
        run: |
          npm install
          echo Node Packages installed
      
      - name: Build
        run: |
          npm run build
          echo Website build ..... Done
          
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: build
          

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Download Artifact
        uses: actions/download-artifact@master
        with: 
          name: dist
          path: build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
